### ISSUE TITLE
Ime repozitorija

### ISSUE THREAD

**Issue by jaanos** [zigamazej/Sigma-total-irregularity-of-bipartite-graphs#1]
@zigamazej, svetujem, da ima repozitorij bolj pomenljivo ime, npr. `Sigma-total-irregularity-of-bipartite-graphs`. Ime spremeniš tako, da zgoraj klikneš na *Settings*, nato pa spremeniš ime pod **Repository name**.

**Comment by marci314** [comment]
Hvala za opozorilo, sem preimenoval.

Lep pozdrav,

Marcel Blagotinšek
